---
deployment:
  tasks:
    - export REPOPATH=/home/kasp7617/repositories/butik-pos
    - export DEPLOYPATH=/home/kasp7617/public_html
    - /bin/cp -rf $REPOPATH/app $DEPLOYPATH/
    - /bin/cp -rf $REPOPATH/bootstrap $DEPLOYPATH/
    - /bin/cp -rf $REPOPATH/config $DEPLOYPATH/
    - /bin/cp -rf $REPOPATH/database $DEPLOYPATH/
    - /bin/cp -rf $REPOPATH/public/css $DEPLOYPATH/public/
    - /bin/cp -rf $REPOPATH/public/js $DEPLOYPATH/public/
    - /bin/cp -f $REPOPATH/public/.htaccess $DEPLOYPATH/public/
    - /bin/cp -f $REPOPATH/public/pull.php $DEPLOYPATH/public/
    - /bin/cp -rf $REPOPATH/resources $DEPLOYPATH/
    - /bin/cp -rf $REPOPATH/routes $DEPLOYPATH/
    - /bin/rm -rf $DEPLOYPATH/storage/framework/views/*
    - /usr/local/bin/php $DEPLOYPATH/artisan config:clear
    - /usr/local/bin/php $DEPLOYPATH/artisan config:cache
    - /usr/local/bin/php $DEPLOYPATH/artisan route:cache
    - /usr/local/bin/php $DEPLOYPATH/artisan view:cache
    - /usr/local/bin/php $DEPLOYPATH/artisan migrate --force
