---
deployment:
  tasks:
    - export DEPLOYPATH=/home/kasp7617/public_html
    - /usr/local/bin/php $DEPLOYPATH/artisan config:clear
    - /usr/local/bin/php $DEPLOYPATH/artisan config:cache
    - /usr/local/bin/php $DEPLOYPATH/artisan route:cache
    - /usr/local/bin/php $DEPLOYPATH/artisan view:cache
    - /usr/local/bin/php $DEPLOYPATH/artisan migrate --force
